### ISSUE TITLE
Error in LocalConstantSigBlobWriter from wrong TypeSig

### ISSUE THREAD

**Issue by tonyredondo** [wwh1004/dnlib#1]
When trying to load an `assembly + pdb` from:

```csharp
using System;

namespace HelloWorld
{
    class Test
    {        
        static void ErrorMethod() 
        {
            const decimal decimalValue = 7922816251426433759354395033M;
        }
    }
}
```

dnlib loads the decimal local constant with a `ClassSig` instead a `ValueTypeSig`.

This cause a problem when trying to write the module again with the PDB, example:
```csharp
                _module.Write(filePath, new ModuleWriterOptions(_module)
                {
                    WritePdb = true
                });
```

In this case the following exception is thrown:
```
dnlib.DotNet.Writer.ModuleWriterException: Expected a null constant
   at dnlib.DotNet.DummyLogger.Log(Object sender, LoggerEvent loggerEvent, String format, Object[] args)
   at dnlib.DotNet.Writer.ModuleWriterBase.dnlib.DotNet.ILogger.Log(Object sender, LoggerEvent loggerEvent, String format, Object[] args)
   at dnlib.DotNet.Writer.Metadata.Error(String message, Object[] args)
   at dnlib.DotNet.Writer.Metadata.dnlib.DotNet.Writer.IWriterError.Error(String message)
   at dnlib.DotNet.Pdb.Portable.LocalConstantSigBlobWriter.Write(DataWriter writer, TypeSig type, Object value)
   at dnlib.DotNet.Pdb.Portable.LocalConstantSigBlobWriter.Write(IWriterError helper, Metadata systemMetadata, DataWriter writer, TypeSig type, Object value)
   at dnlib.DotNet.Writer.Metadata.AddLocalConstant(PdbConstant constant)
   at dnlib.DotNet.Writer.Metadata.WriteMethodBodies()
   at dnlib.DotNet.Writer.Metadata.Create()
   at dnlib.DotNet.Writer.Metadata.CreateTables()
   at dnlib.DotNet.Writer.ModuleWriter.WriteImpl()
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(Stream dest)
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(String fileName)
   at dnlib.DotNet.ModuleDef.Write(String filename, ModuleWriterOptions options)
```

From here: https://github.com/wwh1004/dnlib/blob/master/src/DotNet/Pdb/Portable/LocalConstantSigBlobWriter.cs#L150

If the loader uses a ValueTypeSig I would expect the path to be properly handled by: https://github.com/wwh1004/dnlib/blob/master/src/DotNet/Pdb/Portable/LocalConstantSigBlobWriter.cs#L110

I´m using .NET 5.0 on my tests.

**Comment by wwh1004** [comment]
sorry i don't see this issue because i didn't watch my dnlib fork. i used to use dnspy to save my assembly compiled by latest c# compiler, it threw the same exception. i will try to fix it.

**Comment by wwh1004** [comment]
create an AssemblyResolver to resolve corlib assembly (mscorlib, System.Runtime). if corelib is not resolved, dnlib don't know if a TypeRef is value type and can only return false. the right switch case in writing System.Decimal constant is 'case ElementType.ValueType' not 'case ElementType.Class'.

eg:
``` cs
using var module = ModuleDefMD.Load("1.dll", ModuleDef.CreateModuleContext());
```
